### ISSUE TITLE
Was able to run on dev server, but not production.

### ISSUE THREAD

**Issue by gnosisgithub** [omeka/plugin-OmekaApiImport#4]
Set up exactly the same as I did on development server, but does not work in production.

I get the following errors:
[sklein]$ ./OmekaApiToCsv.php
./OmekaApiToCsv.php: line 1: ?php: No such file or directory
./OmekaApiToCsv.php: line 3: syntax error near unexpected token `'OMEKA_ENDPOINT','
./OmekaApiToCsv.php: line 3:`define('OMEKA_ENDPOINT', 'http://mywebsite.edu/legacy/api');'

any idea?

**Comment by gnosisgithub** [comment]
I run:
sudo php OmekaApiToCsv.php
and returns:
PHP Parse error:  syntax error, unexpected '[' in /var/www/html/OmekaCSV/vendor/guzzlehttp/guzzle/src/functions.php on line 24

any idea?

**Comment by zerocrates** [comment]
Looks like this was filed originally on the wrong repo; the report doesn't appear to relate to this plugin.
