### ISSUE TITLE
Test updates

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-OmekaApiImport#8]
There have been some bugfixes and changes that call for a new round of testing this before release.

The major fix is to deal with problems when the origin Omeka site has Dublin Core Extended, with elements reordered. So, for example, moving one of the extended elements up to the position held by one of the usual DC elements, like Title or Subject. That's without checking the box to overwrite elements. Trying to break the import with lots of that kind of reordering is the biggest mission. After that, it's just doing a bunch of imports from different sites to make sure that that bugfix didn't inadvertently break something else I haven't caught yet.

Use master branch of OmekaApiImport, and probably latest of Omeka (though that shouldn't make a difference).

**Comment by mebrett** [comment]
Tried between some of my sites as well as pulling from other Omeka sites which had a public api. When the source had Extended, the target did add those elements which had data (in my instance, "is part of" showed up on the target installation even without the "override elements" box checked.

No errors on any import, all imports completed and undone successfully.
